import puppeteer from "puppeteer-core";
const b = await puppeteer.launch({ executablePath:"/Applications/Google Chrome.app/Contents/MacOS/Google Chrome", headless:true, protocolTimeout:400000, args:["--no-sandbox"] });
const page = await b.newPage();
await page.setViewport({ width: 1400, height: 860, deviceScaleFactor: 1 });
const cdp = await page.createCDPSession();
await page.goto("http://localhost:3000", { waitUntil:"networkidle2", timeout:60000 });
await page.type('input', "unsplash.com");
await page.evaluate(`(()=>{[...document.querySelectorAll('button')].find(b=>/^Scan/.test((b.textContent||'').trim())).click();})()`);
await page.waitForFunction(`document.querySelectorAll('[role="tab"]').length > 2`, { timeout: 300000 });
await new Promise(r=>setTimeout(r,3000));
await page.evaluate(`(()=>{const t=[...document.querySelectorAll('[role="tab"]')].find(t=>/Images/.test(t.textContent)); t&&t.click();})()`);
await new Promise(r=>setTimeout(r,1500));
await page.evaluate(`(()=>{document.documentElement.style.scrollBehavior='auto';
  const g=document.querySelector('[data-tile]').closest('div.relative'); window.scrollTo(0,g.getBoundingClientRect().top+window.scrollY-40);})()`);
await new Promise(r=>setTimeout(r,6000));
// frame pacing during a fast scroll at 4x throttle
await cdp.send("Emulation.setCPUThrottlingRate",{rate:4});
const gaps = await page.evaluate(`new Promise(res=>{const out=[];let last=performance.now();let n=0;
  function f(now){out.push(now-last);last=now;window.scrollBy(0,110);
    if(++n<150) requestAnimationFrame(f); else res(out.slice(3));} requestAnimationFrame(f);})`);
const q=[...gaps].sort((a,b)=>a-b);
console.log(`fast scroll @4x — median ${q[Math.floor(q.length/2)].toFixed(1)}ms  p90 ${q[Math.floor(q.length*0.9)].toFixed(1)}ms  >50ms ${gaps.filter(g=>g>50).length}/${gaps.length}`);
// scroll-back cache check
let net=0, cached=0;
page.on("response", r=>{ if(r.url().includes("/_next/image")){ net++; if(r.fromCache&&r.fromCache()) cached++; }});
await page.evaluate(`window.scrollBy(0,5000)`); await new Promise(r=>setTimeout(r,2000)); net=0; cached=0;
await page.evaluate(`window.scrollTo(0, document.querySelector('[data-tile]').closest('div.relative').getBoundingClientRect().top + window.scrollY - 40)`);
await new Promise(r=>setTimeout(r,3000));
console.log("scroll-back optimizer responses:", net, "| from cache:", cached);
await b.close();
